/**
 * Interactive CLI Wizard — `db-mcp-server init`
 *
 * Guides the user through configuring a new MCP database server instance.
 * Supports both stdio (Claude Desktop / Cursor) and HTTP transport modes.
 *
 * Pure helper functions are exported separately for testability.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'js-yaml';
import { SERVER_VERSION } from './config.js';
import { generateApiKey } from './auth.js';
import type { DatabaseCredentials } from './types.js';

// ─── ANSI Colors (no chalk dependency) ──────────────────────────────────────

const c = {
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
};

// ─── Types ──────────────────────────────────────────────────────────────────

export interface InitFlags {
  /** --yes: skip prompts, use all defaults */
  yes?: boolean;
  /** --config: output path (default: ./db-mcp-server.yaml) */
  config?: string;
}

export interface InitAnswers {
  transportMode: 'stdio' | 'http';
  dbType: 'postgres' | 'mysql' | 'clickhouse';
  host: string;
  port: number;
  username: string;
  password: string;
  database: string;
  sslMode: 'disable' | 'require' | 'verify-ca' | 'verify-full';
  httpPort?: number;
  apiKey?: string;
}

// ─── Pure Helper Functions (exported for testing) ───────────────────────────

/**
 * Return the default database port for a given db type.
 */
export function getDefaultPort(dbType: string): number {
  switch (dbType) {
    case 'postgres':
      return 5432;
    case 'mysql':
      return 3306;
    case 'clickhouse':
      return 8123;
    default:
      return 5432;
  }
}

/**
 * Return the default username for a given db type.
 */
export function getDefaultUsername(dbType: string): string {
  switch (dbType) {
    case 'postgres':
      return 'postgres';
    case 'mysql':
      return 'root';
    case 'clickhouse':
      return 'default';
    default:
      return 'readonly';
  }
}

/**
 * Return the default database name for a given db type.
 */
function getDefaultDatabase(dbType: string): string {
  switch (dbType) {
    case 'postgres':
      return 'postgres';
    case 'mysql':
      return '';
    case 'clickhouse':
      return 'default';
    default:
      return 'postgres';
  }
}

/**
 * Build the stdio env-config JSON strings for the Claude Desktop snippet.
 *
 * Returns `{ credentials, config }` where both are JSON strings:
 * - credentials: connection details (host, port, username, password, etc.)
 * - config: db_type + security rules (allowed_tables, masking_rules, row_filters)
 */
export function buildStdioEnvConfig(answers: InitAnswers): { credentials: string; config: string } {
  const credentials = JSON.stringify({
    host: answers.host,
    port: answers.port,
    username: answers.username,
    password: answers.password,
    database: answers.database,
    db_type: answers.dbType,
    ssl_mode: answers.sslMode,
  });

  const config = JSON.stringify({
    db_type: answers.dbType,
    allowed_tables: [],
    masking_rules: [],
    row_filters: [],
  });

  return { credentials, config };
}

/**
 * Build the HTTP YAML config file content.
 *
 * SECURITY: Uses environment variable placeholders for sensitive values:
 * - password  -> ${DB_PASSWORD}
 * - api_key   -> ${MCP_API_KEY}
 */
export function buildHttpYamlConfig(answers: InitAnswers): string {
  const doc = {
    server: {
      port: answers.httpPort ?? 8443,
      api_key: '${MCP_API_KEY}',
    },
    database: {
      type: answers.dbType,
      host: answers.host,
      port: answers.port,
      username: answers.username,
      password: '${DB_PASSWORD}',
      database: answers.database,
      ssl_mode: answers.sslMode,
    },
    security: {
      allowed_tables: [],
      masking_rules: [],
      row_filters: [],
    },
  };

  return `# Generated by db-mcp-server init\n${yaml.dump(doc, { lineWidth: 120, quotingType: "'", forceQuotes: false })}`;
}

// ─── Platform Helpers ───────────────────────────────────────────────────────

/**
 * Return the platform-specific path for the Claude Desktop config file.
 */
function getClaudeConfigPath(): string {
  if (process.platform === 'darwin') return '~/Library/Application Support/Claude/claude_desktop_config.json';
  if (process.platform === 'win32') return '%APPDATA%\\Claude\\claude_desktop_config.json';
  return '~/.config/Claude/claude_desktop_config.json';
}

// ─── Connection Test ────────────────────────────────────────────────────────

/**
 * Test the database connection with a 10-second timeout.
 * Always closes the driver in a finally block to prevent connection leaks.
 *
 * @returns `true` if the ping succeeded, `false` otherwise.
 */
async function testConnection(credentials: DatabaseCredentials): Promise<{ ok: boolean; error?: string }> {
  const { createDriver } = await import('./driver-factory.js');
  const driver = createDriver(credentials);

  try {
    const timeoutMs = 10_000;
    let timer: ReturnType<typeof setTimeout>;
    const timeoutPromise = new Promise<never>((_, reject) => {
      timer = setTimeout(() => reject(new Error('Connection timed out after 10 seconds')), timeoutMs);
    });

    try {
      await Promise.race([driver.ping(), timeoutPromise]);
    } finally {
      clearTimeout(timer!);
    }

    return { ok: true };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, error: message };
  } finally {
    await driver.close();
  }
}

// ─── Main Wizard ────────────────────────────────────────────────────────────

/**
 * Run the interactive init wizard.
 *
 * Collects transport mode, database type, connection details, and optional
 * HTTP settings. Tests the connection, then writes config or prints a snippet.
 */
export async function runInit(flags: InitFlags): Promise<void> {
  // Dynamically import @inquirer/prompts (ESM, tree-shakeable)
  const { select, input, password: passwordPrompt, confirm } = await import('@inquirer/prompts');

  // ExitPromptError is thrown on Ctrl+C — we need the class to catch it.
  // It is exported from @inquirer/prompts.
  const inquirerModule = await import('@inquirer/prompts');
  const ExitPromptError = (inquirerModule as Record<string, unknown>).ExitPromptError as
    | (new (...args: unknown[]) => Error)
    | undefined;

  const configPath = flags.config ?? './db-mcp-server.yaml';

  try {
    // ── Step 1: Welcome Banner ────────────────────────────────────────
    console.log('');
    console.log(c.bold(`  db-mcp-server v${SERVER_VERSION}`));
    console.log(c.dim('  Interactive setup wizard'));
    console.log('');

    let answers: InitAnswers;

    if (flags.yes) {
      // ── Non-interactive mode: use all defaults ────────────────────
      answers = {
        transportMode: 'stdio',
        dbType: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: '',
        database: 'postgres',
        sslMode: 'disable',
      };
    } else {
      // ── Step 2: Transport Mode ──────────────────────────────────────
      const transportMode = await select<'stdio' | 'http'>({
        message: 'Transport mode',
        choices: [
          { value: 'stdio', name: 'stdio  — embedded in Claude Desktop / Cursor' },
          { value: 'http', name: 'http   — standalone HTTP server' },
        ],
      });

      // ── Check existing config (HTTP mode only) ──────────────────────
      if (transportMode === 'http' && fs.existsSync(configPath)) {
        const overwrite = await confirm({
          message: `Config file ${configPath} already exists. Overwrite?`,
          default: false,
        });
        if (!overwrite) {
          console.log(c.yellow('Aborted. Existing config file was not modified.'));
          return;
        }
      }

      // ── Step 3: Database Type ───────────────────────────────────────
      const dbType = await select<'postgres' | 'mysql' | 'clickhouse'>({
        message: 'Database type',
        choices: [
          { value: 'postgres', name: 'PostgreSQL' },
          { value: 'mysql', name: 'MySQL / MariaDB' },
          { value: 'clickhouse', name: 'ClickHouse' },
        ],
      });

      // ── Step 4: Connection Details ──────────────────────────────────
      const host = await input({
        message: 'Database host',
        default: 'localhost',
      });

      const portStr = await input({
        message: 'Database port',
        default: String(getDefaultPort(dbType)),
        validate: (val) => {
          const n = Number(val);
          if (!Number.isInteger(n) || n < 1 || n > 65535) return 'Port must be an integer between 1 and 65535';
          return true;
        },
      });
      const port = Number(portStr);

      const username = await input({
        message: 'Database username',
        default: getDefaultUsername(dbType),
      });

      const pw = await passwordPrompt({
        message: 'Database password',
        mask: '*',
      });

      const database = await input({
        message: 'Database name',
        default: getDefaultDatabase(dbType),
      });

      const sslMode = await select<'disable' | 'require' | 'verify-ca' | 'verify-full'>({
        message: 'SSL mode',
        choices: [
          { value: 'disable', name: 'disable' },
          { value: 'require', name: 'require' },
          { value: 'verify-ca', name: 'verify-ca' },
          { value: 'verify-full', name: 'verify-full' },
        ],
        default: 'disable',
      });

      answers = { transportMode, dbType, host, port, username, password: pw, database, sslMode };

      // ── Step 5: HTTP-specific Options ───────────────────────────────
      if (transportMode === 'http') {
        const httpPortStr = await input({
          message: 'HTTP server port',
          default: '8443',
          validate: (val) => {
            const n = Number(val);
            if (!Number.isInteger(n) || n < 1 || n > 65535) return 'Port must be an integer between 1 and 65535';
            return true;
          },
        });
        answers.httpPort = Number(httpPortStr);

        const key = generateApiKey();
        answers.apiKey = key;
        console.log('');
        console.log(c.cyan('  Generated API key:'));
        console.log(c.bold(`  ${key}`));
        console.log(c.dim('  Save this key — it will not be shown again.'));
        console.log('');
      }
    }

    // ── Step 6: Connection Test ─────────────────────────────────────────
    const credentials: DatabaseCredentials = {
      host: answers.host,
      port: answers.port,
      username: answers.username,
      password: answers.password,
      database: answers.database,
      db_type: answers.dbType,
      ssl_mode: answers.sslMode,
    };

    console.log('');
    console.log(c.dim('  Testing connection...'));

    const result = await testConnection(credentials);

    if (result.ok) {
      console.log(c.green('  \u2714 Connection successful'));
    } else {
      console.log(c.red(`  \u2718 Connection failed: ${result.error}`));

      if (flags.yes) {
        // Non-interactive: warn but continue
        console.log(c.yellow('  Continuing anyway (--yes mode).'));
      } else {
        const continueAnyway = await confirm({
          message: 'Continue anyway?',
          default: false,
        });
        if (!continueAnyway) {
          console.log(c.yellow('  Aborted.'));
          return;
        }
      }
    }

    console.log('');

    // ── Step 7: Write Config / Show Output ──────────────────────────────
    if (answers.transportMode === 'stdio') {
      printStdioConfig(answers);
    } else {
      writeHttpConfig(answers, configPath);
    }

    // ── Step 8: Next Steps ──────────────────────────────────────────────
    printNextSteps(answers, configPath);
  } catch (err: unknown) {
    // Handle Ctrl+C gracefully
    if (ExitPromptError && err instanceof ExitPromptError) {
      console.log('');
      console.log('Aborted.');
      return;
    }
    // Also catch by name for resilience (in case the class import fails)
    if (err instanceof Error && err.name === 'ExitPromptError') {
      console.log('');
      console.log('Aborted.');
      return;
    }

    const message = err instanceof Error ? err.message : String(err);
    console.error(c.red(`Error: ${message}`));
    process.exit(1);
  }
}

// ─── Output Helpers ─────────────────────────────────────────────────────────

/**
 * Print the Claude Desktop JSON config snippet (stdio mode).
 *
 * The env block uses literal values because Claude Desktop sets these as
 * process env vars for the spawned MCP server — the config is local to the
 * user's machine and never transmitted over the network.
 */
function printStdioConfig(answers: InitAnswers): void {
  const { credentials, config } = buildStdioEnvConfig(answers);

  const snippet = {
    mcpServers: {
      database: {
        command: 'npx',
        args: ['-y', '@nucleusenterprise/mcp-database-server'],
        env: {
          DB_CREDENTIALS: credentials,
          DB_CONFIG: config,
        },
      },
    },
  };

  const claudeConfigPath = getClaudeConfigPath();

  console.log(c.bold('  Add this to your Claude Desktop config:'));
  console.log(c.dim(`  ${claudeConfigPath}`));
  console.log('');
  console.log(JSON.stringify(snippet, null, 2));
  console.log('');
}

/**
 * Write the HTTP YAML config file.
 *
 * SECURITY:
 * - Password is stored as ${DB_PASSWORD} placeholder, NOT the literal value.
 * - API key is stored as ${MCP_API_KEY} placeholder.
 * - File permissions are set to 0600 (owner read/write only).
 */
function writeHttpConfig(answers: InitAnswers, configPath: string): void {
  const yamlContent = buildHttpYamlConfig(answers);
  const resolvedPath = path.resolve(configPath);

  fs.writeFileSync(resolvedPath, yamlContent, 'utf-8');
  fs.chmodSync(resolvedPath, 0o600);

  console.log(c.green(`  \u2714 Config written to ${resolvedPath}`));
  console.log(c.dim('  File permissions set to 0600 (owner read/write only).'));
  console.log('');

  // Remind user to set environment variables for secrets
  console.log(c.yellow('  Set the following environment variables before starting the server:'));
  console.log('');
  if (answers.apiKey) {
    console.log(`    export MCP_API_KEY="${answers.apiKey}"`);
  } else {
    console.log('    export MCP_API_KEY="<your-api-key>"');
  }
  console.log('    export DB_PASSWORD="<your-database-password>"');
  console.log('');
}

/**
 * Print next-steps instructions for the chosen transport mode.
 */
function printNextSteps(answers: InitAnswers, configPath: string): void {
  console.log(c.bold('  Next steps:'));
  console.log('');

  if (answers.transportMode === 'stdio') {
    const claudeConfigPath = getClaudeConfigPath();
    console.log(`  1. Copy the JSON snippet above into ${c.cyan(claudeConfigPath)}`);
    console.log('  2. Restart Claude Desktop');
    console.log('  3. The "database" MCP server will appear in your tool list');
  } else {
    console.log(`  1. Set environment variables (MCP_API_KEY, DB_PASSWORD)`);
    console.log(`  2. Start the server:`);
    console.log(c.cyan(`     db-mcp-server start --config ${configPath}`));
    console.log(`  3. Connect your MCP client to http://localhost:${answers.httpPort ?? 8443}`);
  }

  console.log('');
  console.log(c.dim('  Documentation: https://github.com/nucleusenterpriseai/database-mcp-server'));
  console.log('');
}
